sudo: required
services:
    - docker

before_install:
    - docker build -t ajaygaur1984/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ajaygaur1984/react-test npm run test -- --coverage

after_success:
    - docker build -t ajaygaur1984/multi-client ./client
    - docker build -t ajaygaur1984/multi-nginx ./nginx
    - docker build -t ajaygaur1984/multi-server ./server
    - docker build -t ajaygaur1984/multi-worker ./worker

    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    ## Take those images and push them to docker hub
    - docker push ajaygaur1984/multi-client
    - docker push ajaygaur1984/multi-server
    - docker push ajaygaur1984/multi-nginx
    - docker push ajaygaur1984/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-775733607082
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

