sudo: required
services:
    - docker

before_install:
    - docker build -t ajaygaur1984/react-test -f ./client/dockderfile.dev ./client

script:
    - docker run -e CI=true ajaygaur1984/react-test npm run test -- --coverage

after_success:
    - docker build -t ajaygaur1984/multi-client ./client
    - docker build -t ajaygaur1984/multi-client ./nginx
    - docker build -t ajaygaur1984/multi-client ./server
    - docker build -t ajaygaur1984/multi-client ./worker

    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    ## Take those images and push them to docker hub
    - docker push ajaygaur1984/multi-client
    - docker push ajaygaur1984/multi-server
    - docker push ajaygaur1984/multi-nginx
    - docker push ajaygaur1984/multi-worker